# Fichier: Dockerfile.python
# Description: Image Docker unique pour tous les services Python.

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# La commande à exécuter sera spécifiée dans docker-compose.yml